spring:
  datasource:
    url: ${mssql-config.connection.url:}
    hikari:
      connectionTimeout: ${mssql-config.connection.timeout:60000}
      minimumPoolSize: ${mssql-config.connection.min-pool-size:5}
      maximumPoolSize: ${mssql-config.connection.max-pool-size:20}
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect

mssql-config:
  connection:
    url: jdbc:sqlserver://localhost:1433;databaseName=query;username=sa;password=5Kn5F%ryzU
    timeout: 20000
    min-pool-size: 1
    max-pool-size: 5

